spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
server:
  port: 8000